import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import BootstrapClient from "../components/BootstrapClient";
import { Col, Container, Row } from "react-bootstrap";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light`}>
        <BootstrapClient />
        <Container className="p-3">
          <NavBar />
          {children}
        </Container>
      </body>
    </html>
  );
}
