export const MyEducation = [
  {
    start: "Feb 2024",
    end: "Now",
    pic: "/educations/monash-logo.png",
    width: 150,
    height: 150,
    university: "Monash University",
    city: "Melbourne",
    country: "Australia",
    uniUrl: "https://monash.edu",
    majorUrl:
      "https://www.monash.edu/it/current-students/enrolment/postgraduate-enrolment/master-of-cybersecurity",
    degree: "Master",
    major: "Cybersecurity",
  },
  {
    start: "Sep 2013",
    end: "Oct 2017",
    pic: "/educations/ugm-logo.png",
    width: 150,
    height: 150,
    university: "Gadjah Mada University",
    city: "Yogyakarta",
    country: "Indonesia",
    uniUrl: "https://ugm.ac.id/",
    majorUrl:
      "https://ugm.ac.id/en/prodi/bachelor-in-electronics-and-instrumentation/",
    degree: "Bachelor",
    major: "Electronics and Instrumentation",
  },
];

export const MyTrainings = [
  {
    end: "Jul 2024",
    desc: "In this module, we learned about the entire penetration testing process, how it is created, its essential components, and how it is divided into the corresponding stages. This will make it very easy for us to find our way around each stage as we follow the process and quickly find out which parts of the process we need to work on to improve.",
    title: "Penetration Testing Process",
    vendor: "Hack The Box",
    vendorUrl: "https://academy.hackthebox.com/",
    place: "Online",
    certificate: "https://academy.hackthebox.com/achievement/888841/90",
    pic: "/trainings/pentest-process.webp",
    width: 200,
    height: 100,
  },
  {
    end: "Oct 2023",
    desc: "Lorem ipsum dolor amet sit",
    title: "Certified Ethical Hacker (CEH)",
    vendor: "Course-Net",
    vendorUrl: "https://course-net.com/",
    place: "Jakarta, Indonesia",
    certificate:
      "https://aspen.eccouncil.org/VerifyBadge?type=certification&a=GBQY5AAA3sD50ztAFKVv5N3j9syaGHcmG+a9xSVvjNM=",
    pic: "/trainings/CEH_2E345519D3F7.png",
    width: 100,
    height: 100,
  },
  {
    end: "Sep 2023",
    desc: "Lorem ipsum dolor amet sit",
    title: "Introduction to Cyber Attacks",
    vendor: "Coursera",
    vendorUrl: "https://www.coursera.org",
    place: "Online",
    certificate:
      "https://www.coursera.org/account/accomplishments/verify/E2W282PC2T49",
    pic: "/trainings/coursera-1.png",
    width: 100,
    height: 100,
  },
  {
    end: "Jul 2023",
    desc: "Lorem ipsum dolor amet sit",
    title: "Building RESTful APIs with Node.js and Express (2019)",
    vendor: "LinkedIn Learning",
    vendorUrl: "https://www.linkedin.com/learning",
    place: "Online",
    certificate:
      "https://www.linkedin.com/learning/certificates/bc5c18eb864736403bd30d60083cde2e975057ec18afceb74b85ee69404fabd8?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_certifications_details%3BhT5t%2FQ3zQiSC8DNFJ0awRg%3D%3D&accountId=2046060&u=2046060&success=true&authUUID=CGJus5ocTRSja8h%2B9iVjnQ%3D%3D",
    pic: "/trainings/linkedin-1.jpg",
    width: 100,
    height: 100,
  },
  {
    end: "Jul 2023",
    desc: "Lorem ipsum dolor amet sit",
    title: "Networking Basics",
    vendor: "Cisco Networking Academy",
    vendorUrl: "https://skillsforall.com/",
    place: "Online",
    certificate:
      "https://www.credly.com/badges/2c18a889-9cd8-4ea5-805c-ab65c8f19662/linked_in_profile",
    pic: "/trainings/networking-basics.png",
    width: 100,
    height: 100,
  },
  {
    end: "Jun 2023",
    desc: "Lorem ipsum dolor amet sit",
    title: "Introduction to Cybersecurity",
    vendor: "Cisco Networking Academy",
    vendorUrl: "https://skillsforall.com/",
    place: "Online",
    certificate:
      "https://www.credly.com/badges/e0a4a41f-5151-4bc6-955d-22e7040a1e5c/linked_in_profile",
    pic: "/trainings/introduction-to-cybersecurity.png",
    width: 100,
    height: 100,
  },
  {
    end: "Jun 2020",
    desc: "Lorem ipsum dolor amet sit",
    title: "ReactJs Web Frontend",
    vendor: "Sanbercode",
    vendorUrl: "https://sanbercode.com/",
    place: "Online",
    certificate:
      "https://sanbercode.com/sertifikat/generate/f5cff4be-8753-4d17-9a63-09744829fc6e",
    pic: "/trainings/sanbercode.png",
    width: 100,
    height: 100,
  },
];
